module.exports = {
    CREATE_USER: 'CREATE_USER',
    PUSH_WORD: 'PUSH_WORD',
    UPDATE_DEV_MODE: 'UPDATE_DEV_MODE',
    SEND_NAME: 'SEND_NAME',
    POST_USER: 'POST_USER',
    WAKE_UP_SERVER: 'WAKE_UP_SERVER',
}